steps:
  #Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
        'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}', '.']

 #Docker Push 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}']
options:
  logging: CLOUD_LOGGING_ONLY

